-- AlterTable
ALTER TABLE "workplaces" ADD COLUMN     "comments" TEXT,
ADD COLUMN     "computer_type" VARCHAR(20),
ADD COLUMN     "floor" INTEGER,
ADD COLUMN     "headphones_brand" VARCHAR(100),
ADD COLUMN     "headphones_model" VARCHAR(100),
ADD COLUMN     "hostname" VARCHAR(100),
ADD COLUMN     "ip_address" VARCHAR(15),
ADD COLUMN     "keyboard_brand" VARCHAR(100),
ADD COLUMN     "keyboard_model" VARCHAR(100),
ADD COLUMN     "mac_address" VARCHAR(17),
ADD COLUMN     "monitor_brand" VARCHAR(100),
ADD COLUMN     "monitor_model" VARCHAR(100),
ADD COLUMN     "monitor_serial" VARCHAR(100),
ADD COLUMN     "mouse_brand" VARCHAR(100),
ADD COLUMN     "mouse_model" VARCHAR(100),
ADD COLUMN     "pc_brand" VARCHAR(100),
ADD COLUMN     "pc_model" VARCHAR(100),
ADD COLUMN     "pc_serial" VARCHAR(100),
ADD COLUMN     "processor" VARCHAR(150),
ADD COLUMN     "ram" VARCHAR(50),
ADD COLUMN     "room" INTEGER,
ADD COLUMN     "storage" VARCHAR(150);
